API_BASE_URI = 'http://www.listadacidade.com.br/services'
API_FEDERATION_UNIT_URI = API_BASE_URI + '/estado.php'
API_CITY_URI = API_BASE_URI + '/city.php'
API_GROUP_URI = API_BASE_URI + '/grupo.php'
API_SUBGROUP_URI = API_BASE_URI + '/subgrupo.php'