# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c7b95ab48b4c210a76ffd3ff64504242179713fa87d6c4644da53ad14ec5e9de870909585f06afaa51c8e1a75a924e7496ca185fc1621fc10c6c5956fab7e67

test:
  secret_key_base: 636d265d4dfefb4c2ba358fc865dc328422070abb1df404b405191a1cd067f21d44cc978874a406760bb79dddcb0b4a099450b1fa666e0bfd6915d4120079626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
