require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProductionOrdersController do

  # This should return the minimal set of attributes required to create a valid
  # ProductionOrder. As you add validations to ProductionOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductionOrdersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all production_orders as @production_orders" do
      production_order = ProductionOrder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:production_orders).should eq([production_order])
    end
  end

  describe "GET show" do
    it "assigns the requested production_order as @production_order" do
      production_order = ProductionOrder.create! valid_attributes
      get :show, {:id => production_order.to_param}, valid_session
      assigns(:production_order).should eq(production_order)
    end
  end

  describe "GET new" do
    it "assigns a new production_order as @production_order" do
      get :new, {}, valid_session
      assigns(:production_order).should be_a_new(ProductionOrder)
    end
  end

  describe "GET edit" do
    it "assigns the requested production_order as @production_order" do
      production_order = ProductionOrder.create! valid_attributes
      get :edit, {:id => production_order.to_param}, valid_session
      assigns(:production_order).should eq(production_order)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProductionOrder" do
        expect {
          post :create, {:production_order => valid_attributes}, valid_session
        }.to change(ProductionOrder, :count).by(1)
      end

      it "assigns a newly created production_order as @production_order" do
        post :create, {:production_order => valid_attributes}, valid_session
        assigns(:production_order).should be_a(ProductionOrder)
        assigns(:production_order).should be_persisted
      end

      it "redirects to the created production_order" do
        post :create, {:production_order => valid_attributes}, valid_session
        response.should redirect_to(ProductionOrder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved production_order as @production_order" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductionOrder.any_instance.stub(:save).and_return(false)
        post :create, {:production_order => {  }}, valid_session
        assigns(:production_order).should be_a_new(ProductionOrder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductionOrder.any_instance.stub(:save).and_return(false)
        post :create, {:production_order => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested production_order" do
        production_order = ProductionOrder.create! valid_attributes
        # Assuming there are no other production_orders in the database, this
        # specifies that the ProductionOrder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProductionOrder.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => production_order.to_param, :production_order => { "these" => "params" }}, valid_session
      end

      it "assigns the requested production_order as @production_order" do
        production_order = ProductionOrder.create! valid_attributes
        put :update, {:id => production_order.to_param, :production_order => valid_attributes}, valid_session
        assigns(:production_order).should eq(production_order)
      end

      it "redirects to the production_order" do
        production_order = ProductionOrder.create! valid_attributes
        put :update, {:id => production_order.to_param, :production_order => valid_attributes}, valid_session
        response.should redirect_to(production_order)
      end
    end

    describe "with invalid params" do
      it "assigns the production_order as @production_order" do
        production_order = ProductionOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductionOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => production_order.to_param, :production_order => {  }}, valid_session
        assigns(:production_order).should eq(production_order)
      end

      it "re-renders the 'edit' template" do
        production_order = ProductionOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductionOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => production_order.to_param, :production_order => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested production_order" do
      production_order = ProductionOrder.create! valid_attributes
      expect {
        delete :destroy, {:id => production_order.to_param}, valid_session
      }.to change(ProductionOrder, :count).by(-1)
    end

    it "redirects to the production_orders list" do
      production_order = ProductionOrder.create! valid_attributes
      delete :destroy, {:id => production_order.to_param}, valid_session
      response.should redirect_to(production_orders_url)
    end
  end

end
